collections_config:
  events:
    name: Events
    output: true
    icon: celebration
    image_key: image
    schemas:
      default:
        path: schemas/events.md
  partners:
    name: Partners
  people:
    name: People
    _hide_content: true
    output: true
  videos:
    name: Videos
    output: true
  # posts:
  #   name: Posts


# data_config:

source: src

timezone: Pacific/Auckland

paths:
  collections: collections
  # uploads: uploads

