upcoming_event_bar:
  active: true
  event_short_title: TEDxAkl 2023
  left: UPCOMING
  right: TEDxAuckland 2023, Sun 3rd Dec
buy_ticket_button:
  active: true
  url: https://tedxauckland.com/community/events#/2023/tickets/purchase
navigation:
  - title: Talks/
    sub_title: Ideas
    url: /talks/
  - title: Events/
    sub_title: Experiences
    url: /events/
  - title: Partnerships/
    sub_title: Sponsors
    url: /partners/
  - title: Blog/
    sub_title: News
    url: /blog/
  - title: About/
    sub_title: Mission
    url: /about/
  - title: Subscribe/
    sub_title: Contact
    url: /join-us/
