upcoming_event_bar:
  active: true
  event_short_title: 'tūmanako'
  left: 'TEDxAuckland: tūmanako'
  right: 'Saturday November 16th, 2019 | ASB Waterfront Theatre'
buy_ticket_button:
  active: true
  url: /events/tumanako/
navigation:
  - title: Talks/
    sub_title: Ideas
    url: /talks/
  - title: Events/
    sub_title: Experiences
    url: /events/
  - title: Partnerships/
    sub_title: Support
    url: /partners/
  - title: Blog/
    sub_title: News
    url: /news/
  - title: About/
    sub_title: Contact
    url: /about/
  - title: Join Us/
    sub_title: /Mailing List
    url: /mailing-list/
