upcoming_event_bar:
  active: true
  event_short_title: Dec '22 | Down To Earth
  left: UPCOMING
  right: 'TEDxAuckland: Down to Earth, Sat Dec 3rd 2022 #bethere'
buy_ticket_button:
  active: true
  url: >-
    https://tedxauckland.com/community/events#/down-to-earth-2022/tickets/purchase
navigation:
  - title: Talks/
    sub_title: Ideas
    url: /talks/
  - title: Events/
    sub_title: Experiences
    url: /events/
  - title: Partnerships/
    sub_title: Sponsors
    url: /partners/
  - title: Blog/
    sub_title: News
    url: /blog/
  - title: About/
    sub_title: Mission
    url: /about/
  - title: Subscribe/
    sub_title: Contact
    url: /join-us/
