upcoming_event_bar:
  active: true
  event_short_title: JUN 2022
  left: UPCOMING
  right: 'TEDxAuckland 2022, June 8th #bethere'
buy_ticket_button:
  active: true
  url: https://tedxauckland.com/community/events#/june-2022/tickets/purchase
navigation:
  - title: Talks/
    sub_title: Ideas
    url: /talks/
  - title: Events/
    sub_title: Experiences
    url: /events/
  - title: Partnerships/
    sub_title: Support
    url: /partners/
  - title: Blog/
    sub_title: News
    url: /news/
  - title: About/
    sub_title: Contact
    url: /about/
  - title: Join Us/
    sub_title: /Mailing List
    url: /mailing-list/