# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TEDxAuckland
description: > # this means to ignore newlines until "baseurl:"
  TEDxAuckland run events that inspire and spread ideas in the greater context of
  Technology, Entertainment and Design. Next event: October 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tedxauckland.com" # the base hostname & protocol for your site
permalink: pretty

twitter:
  username: TEDxAuckland
  card: summary

facebook:
  app_id: 279041479564647
  publisher: 137734816208

social:
  name: TEDxAuckland
  links:
    - https://twitter.com/tedxauckland
    - https://www.facebook.com/TEDxAuckland/
    - https://www.instagram.com/tedxauckland/
    - https://www.youtube.com/user/TEDxAuckland

# Markdown settings
markdown: kramdown
timezone: Pacific/Auckland

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-responsive-image
  - jekyll-seo-tag

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 300
    - width: 600
    - width: 900
    - width: 1200
    - width: 1400
    - width: 1800
    - width: 3800
  output_path_format: assets/resized/%{filename}-%{width}.%{extension}

# Build settings
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - readme.md
  - vendor

collections:
  events:
    name: Events
    output: true
  partners:
    name: Partners
  people:
    name: People
    _hide_content: true
    output: true
  videos:
    name: Videos
    output: true
  posts:
    name: Posts

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: :slug/
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
      permalink: talks/:slug/

_comments:
  short_title: Used in smaller spaces
  start_date: When does the event start?
  end_date: When does the event end?
  people: To add more options add people in explore.
  flikr_gallery: The url to the flikr gallery. Leave blank if N/A.
  youtube_playlist: The url to the youtube playlist. Leave blank if N/A.
  ticket_url: Where can people buy tickets. Leave blank if N/A.
