# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tedxauckland.com" # the base hostname & protocol for your site
permalink: pretty

# Markdown settings
markdown: kramdown
timezone: Pacific/Auckland

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 300
    - width: 600
    - width: 900
    - width: 1200
    - width: 1400
    - width: 1800
    - width: 3800

# Build settings
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - readme.md

navigation:
  - title: Talks/
    sub_title: Ideas
    url: /talks/
  - title: Events/
    sub_title: Experiences
    url: /events/
  - title: Blog/
    sub_title: News
    url: /news/
  - title: About/
    sub_title: Contact
    url: /about/

collections:
  events:
    name: Events
    output: true
  partners:
    name: Partners
  people:
    name: People
    _hide_content: true
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: :slug/

_comments:
  short_title: Used in smaller spaces
  start_date: When does the event start?
  end_date: When does the event end?
  people: To add more options add people in explore.
  flikr_gallery: The url to the flikr gallery. Leave blank if N/A.
  youtube_playlist: The url to the youtube playlist. Leave blank if N/A.
  ticket_url: Where can people buy tickets. Leave blank if N/A.
