source 'https://rubygems.org'

gem 'jekyll', '~> 3.8', '>= 3.8.5'
gem 'yt', '~> 0.32.2'
gem 'bigdecimal', '~> 1.3', '>= 1.3.5'
gem 'flickr-objects', '~> 0.6.3'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-autoprefixer'
  # gem 'jekyll-responsive-image', github: 'JacobKorn/jekyll-responsive-image', branch: 'custom-sizes'
  gem 'jekyll-responsive-image', path: '../../jekyll-responsive-image/'
  gem 'jekyll-seo-tag'
end
