source 'https://rubygems.org'

gem 'jekyll'
gem 'bigdecimal'
gem 'webrick'
gem 'execjs', '2.7.0'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-autoprefixer'
  gem 'jekyll-responsive-image', github: 'JacobKorn/jekyll-responsive-image', branch: 'custom-sizes-update'
  gem 'jekyll-seo-tag'
end
