source 'https://rubygems.org'

gem 'jekyll', '3.7.3'
gem 'yt'
gem 'bigdecimal'
gem 'flickr-objects'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-autoprefixer'
  gem 'jekyll-responsive-image', :path => "../jekyll-responsive-image"
end
